# Generated by Django 3.2.9 on 2022-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Setting Up', 'Setting Up'), ('Connected', 'Connected')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Monthly', 'Monthly')], max_length=200, null=True),
        ),
    ]
