# Generated by Django 3.2.9 on 2022-05-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220511_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='plan',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
