# Generated by Django 3.2.9 on 2022-05-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220511_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
