# Generated by Django 3.2.9 on 2022-05-14 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_failedloginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedloginattempt',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
